# Generated by Django 5.0.3 on 2024-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='priority',
            field=models.CharField(choices=[('need', 'need'), ('want', 'want')], default='need', max_length=100),
        ),
    ]
